error_fun_ret3.nit:17,5--8: Error: reached end of function; expected `return` with a value.
