error_spe_fun.nit:23,11--14: Error: reached end of function; expected `return` with a value.
